### ISSUE TITLE
urlBase stopped working from 1.8.0 to latest

### ISSUE THREAD

**Issue by ifsnop** [bpatrik/pigallery2#178]
**Describe the bug**
I installed pigallery2 from github (clone repository), and let pigallery2 generate a new fresh config.json. Everything works as expected. After modifying config.json to use publicUrl and urlBase, site stopped working when accesing using the reverse proxy.  Same configuration works ok in 1.8.0, so I think this is a regression.

Using the console view from chrome, shows that no urlBase is getting appended to host when requesting styles...css, runtime...js,  polyfills...js or main...js. The server returns 404.

It wass correctly appended in 1.8.0. Calls to api/notifications get the urlBase appended to the host.

**Environment (please complete the following information):**
 - OS: debian
 - Browser: doesn't matter, tried Chrome and Explorer

**Used app version**:
- compiled from source (git clone).

**Comment by bpatrik** [comment]
Hi,

Thank you for reporting, I know about the issue a fix should come shortly.

**Comment by bpatrik** [comment]
The latest commit should fix this

**Comment by ifsnop** [comment]
I can confirm this. Thanks!!

**Comment by emmericp** [comment]
i'm seeing this on the current nightly-stretch docker container

**Comment by binerf** [comment]
Hi,

Sorry, I'm still facing this issue, I guess that's similar actually.
Loading URL in browser and getting "Loading" with icon of missing image... then nothing else.

**Describe the bug**
css, runtime...js, polyfills...js or main...js. The server returns 404.

**Environment (please complete the following information):**

- OS: Ubuntu
- Browser: doesn't matter, tried Chrome and Firefox
- Apache2 as reverse proxy including conf:
```
       ProxyPass /pigallery2/ http://127.0.0.1:8085/
       ProxyPassReverse /pigallery2/ http://127.0.0.1:8085/
```


**Used app version:**

- Docker image: bpatrik/pigallery2:latest
- Apache2 as reverse-rpxoy

**Comment by bpatrik** [comment]
Thanks. I'll look into it. 
In the mean time pls. make sure that you set up your urlBase the proper way in the settings.

**Comment by binerf** [comment]
Thanks for looking into this issue.

Checked the `config.json` file:
`        "urlBase": "/pigallery2",`

**Comment by bpatrik** [comment]
Can you check if this still an issue with the nigthly build ? (or with 1.8.5)
I think this should work now.

**Comment by binerf** [comment]
Hello,

Unfortunately, problem persists.

I've updated my _docker-compose.yml_ to use _bpatrik/pigallery2:nightly-alpine_ and cleaned my browser cache but I'm still facing this issue...

**Comment by bpatrik** [comment]
That is odd. It works for others (https://github.com/bpatrik/pigallery2/issues/264#issuecomment-823156514). 
Did you also explicitly pull this newer version, docker does not do that for you. 

Is it properly set up? (like no typo, right place in the json) If you can open the app, you can double check it on the UI (if it shows up, it works)

**Comment by binerf** [comment]
I'm getting crazy.

I've removed all docker images related to _pigallery2_.

Checked `config.json` file.

Checked Apache configuration:
```
        <Location /pigallery2>
                ProxyPass http://127.0.0.1:8085
                ProxyPassReverse http://127.0.0.1:8085
        </Location>

```

Started container based on `bpatrik/pigallery2:nightly-alpine`.

I'm still facing the same issue.

I don't get it.

BTW, when I use web developer function in Firefox, I get some errors like:
```
GET https://www.mydomain.com/assets/icon.png
Status404
Not Found
VersionHTTP/2
Transferred402 B (276 B size)
Referrer Policystrict-origin-when-cross-origin
```
(_mydomain.com_ has been changed for this report)

**Comment by bpatrik** [comment]
Does this help? https://github.com/bpatrik/pigallery2/issues/152#issuecomment-614459658
I never used apache, so I'm not sure how to set that up.
This:
```
GET https://www.mydomain.com/assets/icon.png
Status404
```
means that you do not have a `urlBase` setup:
```
"publicUrl": "",
 "urlBase": "",
```

Otherwise if ` "urlBase": "/test"`, the request would have been ` https://www.mydomain.com/test/assets/icon.png`

**Comment by binerf** [comment]
OK problem fixed !!! Thanks.

Here, what I did:
1. Stop container
2. Backup `config.json` file
3. Delete `config.json` file
4. Start container (an "empty" `config.json` file is generated)
5. Stop container
6. Update `config.json` file according to my configuration (_publicUrl_ and _urlBase_ settings only)
7. Start container
8. Access _pigallery2_ interface
9. Rulez !
Thanks!!

**Comment by bpatrik** [comment]
Super! I'm happy to hear!
